# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/fr
  # title: Titre en français
  params:
    description: CV académique de Jaël Champagne Gareau, chercheur postdoctoral à l'Université TÉLUQ
  # menu:
  #   main:
  #     - name: 传
  #       url: '#about'
  #       weight: 1
